Watching for file changes with StatReloader
"GET /add-task/ HTTP/1.1" 200 2316
"GET /schedule/ HTTP/1.1" 200 20024
"GET /add-task/ HTTP/1.1" 200 2316
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 23692
"POST /submit-feedback/6/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 22886
"POST /submit-feedback/8/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 22080
"POST /submit-feedback/5/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21274
"POST /submit-feedback/7/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 20468
"GET /schedule/ HTTP/1.1" 200 20468
"GET /task_prioritization/ HTTP/1.1" 200 2400
Watching for file changes with StatReloader
"GET /task_prioritization/ HTTP/1.1" 200 2400
"GET /task_prioritization/ HTTP/1.1" 200 2400
"GET /schedule/ HTTP/1.1" 200 20468
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 7961
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 20468
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 20468
Internal Server Error: /analytics/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 303, in task_analytics
    monthly_performance = total_tasks.annotate(
                          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1630, in annotate
    return self._annotate(args, kwargs, select=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1680, in _annotate
    clone.query.add_annotation(
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1198, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\functions\datetime.py", line 287, in resolve_expression
    copy = super().resolve_expression(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\expressions.py", line 975, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\expressions.py", line 854, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 2014, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1867, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_at' into field. Choices are: completed, description, due_date, end_time, estimated_time, has_feedback, id, importance, is_active, predicted_priority, schedule, taskfeedback, taskhistory, title, urgency, user, user_id
"GET /analytics/ HTTP/1.1" 500 117526
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /analytics/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 321, in task_analytics
    avg_task_duration = total_tasks.aggregate(
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 459, in get_aggregation
    aggregate = aggregate_expr.resolve_expression(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\aggregates.py", line 65, in resolve_expression
    c = super().resolve_expression(query, allow_joins, reuse, summarize)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\expressions.py", line 975, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\expressions.py", line 854, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 2014, in resolve_ref
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1867, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'actual_time' into field. Choices are: avg_estimated_time, completed, description, due_date, end_time, estimated_time, has_feedback, id, importance, is_active, predicted_priority, schedule, taskfeedback, taskhistory, title, urgency, user, user_id
"GET /analytics/ HTTP/1.1" 500 113955
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /analytics/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 347, in task_analytics
    return render(request, 'task_analytics.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /analytics/ HTTP/1.1" 500 208762
"GET /analytics/ HTTP/1.1" 200 2377
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /analytics/ HTTP/1.1" 200 2377
"GET /analytics/ HTTP/1.1" 200 9134547
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /analytics/ HTTP/1.1" 200 898
"GET /analytics/ HTTP/1.1" 200 898
"GET /analytics/ HTTP/1.1" 200 898
"GET /analytics/ HTTP/1.1" 200 898
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /analytics/ HTTP/1.1" 200 9134547
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 20468
"GET /add-task/ HTTP/1.1" 200 2316
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET /add-task/ HTTP/1.1" 200 2316
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 20468
"GET /schedule/ HTTP/1.1" 200 20468
"GET /schedule/ HTTP/1.1" 200 20468
"GET /schedule/ HTTP/1.1" 200 20468
"GET /schedule/ HTTP/1.1" 200 20468
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\utils.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 24151
"POST /submit-feedback/13/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 23340
"GET /schedule/ HTTP/1.1" 200 23340
"GET /schedule/ HTTP/1.1" 200 23340
"GET /schedule/ HTTP/1.1" 200 23340
"GET /schedule/ HTTP/1.1" 200 23340
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9244
"GET /schedule/ HTTP/1.1" 200 9244
"GET /schedule/ HTTP/1.1" 200 9244
"GET /schedule/ HTTP/1.1" 200 9244
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 23340
"GET /schedule/ HTTP/1.1" 200 23340
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9244
"GET /add-task/ HTTP/1.1" 200 2316
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 9244
"GET /schedule/ HTTP/1.1" 200 9244
"GET /schedule/ HTTP/1.1" 200 9244
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 27015
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 23340
"GET /schedule/ HTTP/1.1" 200 23340
"GET /schedule/ HTTP/1.1" 200 23340
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 23340
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 12728
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9244
"GET /schedule/ HTTP/1.1" 200 9244
"GET /schedule/ HTTP/1.1" 200 9244
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 12728
"GET /task_prioritization/ HTTP/1.1" 200 2554
"POST /task_prioritization/ HTTP/1.1" 200 2570
"GET /schedule/ HTTP/1.1" 200 12728
"GET /schedule/ HTTP/1.1" 200 12728
"GET /schedule/ HTTP/1.1" 200 12728
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2377
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3738
"GET /login/ HTTP/1.1" 200 7063
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2377
"GET /add-task/ HTTP/1.1" 200 2316
"GET /schedule/ HTTP/1.1" 200 12728
"POST /submit-feedback/14/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 11917
"GET /analytics/ HTTP/1.1" 200 9134547
"GET / HTTP/1.1" 200 2377
"GET /add-task/ HTTP/1.1" 200 2316
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 11917
"GET /schedule/ HTTP/1.1" 200 11917
"GET /schedule/ HTTP/1.1" 200 11917
"GET /schedule/ HTTP/1.1" 200 11917
"GET /schedule/ HTTP/1.1" 200 11917
"GET /schedule/ HTTP/1.1" 200 11917
"GET /schedule/ HTTP/1.1" 200 11917
"GET /schedule/ HTTP/1.1" 200 11917
"GET /analytics/ HTTP/1.1" 200 9134547
"GET / HTTP/1.1" 200 2377
"GET /analytics/ HTTP/1.1" 200 9134547
"GET /schedule/ HTTP/1.1" 200 11917
"GET /task_prioritization/ HTTP/1.1" 200 2652
"GET /task_prioritization/ HTTP/1.1" 200 2652
"GET /task_prioritization/ HTTP/1.1" 200 2652
"GET // HTTP/1.1" 200 2377
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2377
"GET /schedule/ HTTP/1.1" 200 9036
"GET /add-task/ HTTP/1.1" 200 2316
"GET / HTTP/1.1" 200 2377
"GET /login/ HTTP/1.1" 200 7063
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2377
"GET /schedule/ HTTP/1.1" 200 9036
"GET /add-task/ HTTP/1.1" 200 2316
"GET /task_prioritization/ HTTP/1.1" 200 2652
"POST /task_prioritization/ HTTP/1.1" 200 2621
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /task_prioritization/ HTTP/1.1" 200 2621
Internal Server Error: /schedule/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 90, in schedule
    scheduler.dqn_prioritizer.save(MODEL_PATH)
    ^^^^^^^^^
UnboundLocalError: cannot access local variable 'scheduler' where it is not associated with a value
"GET /schedule/ HTTP/1.1" 500 65722
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9036
"GET /schedule/ HTTP/1.1" 200 9036
"GET /schedule/ HTTP/1.1" 200 9036
"GET /schedule/ HTTP/1.1" 200 9036
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\scheduler.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9036
"GET /schedule/ HTTP/1.1" 200 9036
"GET /schedule/ HTTP/1.1" 200 9036
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\reinforcement_learning.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\scheduler.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9036
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\reinforcement_learning.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\scheduler.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9036
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\reinforcement_learning.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9036
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\reinforcement_learning.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9036
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 9036
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 15297
"GET /add-task/ HTTP/1.1" 200 2316
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 18924
Internal Server Error: /schedule/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 139, in schedule
    return render(request, 'schedule_and_feedback.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 178: 'endblock'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 146, in schedule
    return render(request, 'schedule_and_feedback.html', {'daily_schedule': []})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 178: 'endblock'. Did you forget to register or load this tag?
"GET /schedule/ HTTP/1.1" 500 276550
"GET /schedule/ HTTP/1.1" 200 18924
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 18924
Not Found: /]
"GET /] HTTP/1.1" 404 3879
"GET / HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 18924
"GET / HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 18924
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3907
"GET / HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 18924
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 18924
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
Not Found: /add-tastt
"GET /add-tastt HTTP/1.1" 404 3906
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /add-tastt
"GET /add-tastt HTTP/1.1" 404 3906
"GET /home/ HTTP/1.1" 200 5505
"GET /add-task/ HTTP/1.1" 200 2316
"GET /schedule/ HTTP/1.1" 200 18924
"GET /analytics/ HTTP/1.1" 200 9134547
"GET /home/ HTTP/1.1" 200 2572
"GET /schedule/ HTTP/1.1" 200 18924
"GET /home/ HTTP/1.1" 200 2572
"GET /home/ HTTP/1.1" 200 2572
"GET /home/ HTTP/1.1" 200 2572
"GET /home/ HTTP/1.1" 200 2572
"GET /home/ HTTP/1.1" 200 2572
"GET /home/ HTTP/1.1" 200 2572
"GET /home/ HTTP/1.1" 200 2572
"GET /home/ HTTP/1.1" 200 2377
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /home/ HTTP/1.1" 200 2377
"GET /home/ HTTP/1.1" 200 2377
"GET /schedule/ HTTP/1.1" 200 18924
Not Found: /
"GET / HTTP/1.1" 404 3692
"GET /add-task/ HTTP/1.1" 200 2316
"GET /schedule/ HTTP/1.1" 200 18924
"GET /schedule/ HTTP/1.1" 200 21509
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3692
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3743
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3743
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2377
"GET /login/ HTTP/1.1" 200 7063
"POST /login/ HTTP/1.1" 200 7063
"GET / HTTP/1.1" 200 2377
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3738
"POST /login/ HTTP/1.1" 200 7063
"GET /signup/ HTTP/1.1" 200 6001
"POST /login/ HTTP/1.1" 200 7063
"POST /login/ HTTP/1.1" 200 7063
"POST /signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2377
"GET / HTTP/1.1" 200 2377
"GET /login/ HTTP/1.1" 200 7063
"GET /login/ HTTP/1.1" 200 7063
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2377
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2377
"GET /add-task/ HTTP/1.1" 200 2316
"GET /schedule/ HTTP/1.1" 200 21480
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21480
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21480
"GET /schedule/ HTTP/1.1" 200 21480
"GET /schedule/ HTTP/1.1" 200 21480
"GET /schedule/ HTTP/1.1" 200 21480
"GET /schedule/ HTTP/1.1" 200 21480
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 44394
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 21480
"GET /add-task/ HTTP/1.1" 200 2316
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 25620
"GET /schedule/ HTTP/1.1" 200 10280
"GET /add-task/ HTTP/1.1" 200 2316
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
"GET / HTTP/1.1" 200 2377
"GET /schedule/ HTTP/1.1" 200 10280
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10280
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 26003
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 26003
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
"GET /schedule/ HTTP/1.1" 200 10280
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10596
"GET /schedule/ HTTP/1.1" 200 10596
"GET /schedule/ HTTP/1.1" 200 10596
Internal Server Error: /schedule/
Traceback (most recent call last):
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 153, in schedule
    return render(request, 'schedule_and_feedback.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'multiply'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 158, in schedule
    return render(request, 'schedule_and_feedback.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'multiply'
"GET /schedule/ HTTP/1.1" 500 351563
"GET /schedule/ HTTP/1.1" 200 533
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 2052
"GET /schedule/ HTTP/1.1" 200 2052
"GET /schedule/ HTTP/1.1" 200 2052
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /analytics/ HTTP/1.1" 200 9134553
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 26019
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 3832
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 30037
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3738
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 3832
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 34835
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 34835
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 18582
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 18640
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 18640
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 18640
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 3832
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 22752
"GET /schedule/ HTTP/1.1" 200 22752
"GET /schedule/ HTTP/1.1" 200 22752
"GET /schedule/ HTTP/1.1" 200 22752
"GET /schedule/ HTTP/1.1" 200 22752
"POST /submit-feedback/22/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 22752
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 23232
"GET /schedule/ HTTP/1.1" 200 23232
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 39559
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\utils.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\utils.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\utils.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 19576
"GET /schedule/ HTTP/1.1" 200 19576
"GET /schedule/ HTTP/1.1" 200 19576
"GET /schedule/ HTTP/1.1" 200 19576
"GET /schedule/ HTTP/1.1" 200 19576
"GET /schedule/ HTTP/1.1" 200 19576
"GET /schedule/ HTTP/1.1" 200 19576
"GET /schedule/ HTTP/1.1" 200 19576
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 10296
"GET /schedule/ HTTP/1.1" 200 10296
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 39150
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 39150
"GET / HTTP/1.1" 200 2377
"GET /login/ HTTP/1.1" 200 7063
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 2377
Internal Server Error: /add-task/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'add-task'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 59, in add_task
    return render(request, 'add_task.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 131: 'add-task'. Did you forget to register or load this tag?
"GET /add-task/ HTTP/1.1" 500 149328
Internal Server Error: /add-task/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'add-task'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 59, in add_task
    return render(request, 'add_task.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 131: 'add-task'. Did you forget to register or load this tag?
"GET /add-task/ HTTP/1.1" 500 149465
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 3832
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 43261
"GET /analytics/ HTTP/1.1" 200 9134553
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2377
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3738
"GET /schedule/ HTTP/1.1" 200 44565
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 3832
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 48812
"GET /analytics/ HTTP/1.1" 200 9134554
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /analytics/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 353, in task_analytics
    return render(request, 'task_analytics.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
"GET /analytics/ HTTP/1.1" 500 222028
Internal Server Error: /analytics/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 353, in task_analytics
    return render(request, 'task_analytics.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 565, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 79: 'endblock'. Did you forget to register or load this tag?
"GET /analytics/ HTTP/1.1" 500 177442
"GET /analytics/ HTTP/1.1" 200 4573071
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /analytics/ HTTP/1.1" 200 4574909
"GET /analytics/ HTTP/1.1" 200 4573877
"GET /schedule/ HTTP/1.1" 200 48812
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /schedule/ HTTP/1.1" 200 18458
"POST /submit-feedback/20/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17423
"GET /analytics/ HTTP/1.1" 200 4573875
"GET /schedule/ HTTP/1.1" 200 17423
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 3832
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21600
"GET /schedule/ HTTP/1.1" 200 21600
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2377
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3738
"GET /schedule/ HTTP/1.1" 200 21600
"GET /analytics/ HTTP/1.1" 200 4574333
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2377
"GET /schedule/ HTTP/1.1" 200 21600
"GET /analytics/ HTTP/1.1" 200 4574333
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\Ai_Task_Mang\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /analytics/ HTTP/1.1" 200 4574333
"GET /schedule/ HTTP/1.1" 200 21600
"GET /schedule/ HTTP/1.1" 200 21600
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\notification.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2377
"GET /schedule/ HTTP/1.1" 200 21600
"GET /schedule/ HTTP/1.1" 200 21600
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 27, in home
    return render(request, 'home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add-task' not found. 'add-task' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 115801
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 27, in home
    return render(request, 'home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'analytics' not found. 'analytics' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 115865
"GET / HTTP/1.1" 200 2748
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
"GET / HTTP/1.1" 200 3097
"GET /login/ HTTP/1.1" 200 7063
"GET / HTTP/1.1" 200 3097
"GET / HTTP/1.1" 200 3108
"GET / HTTP/1.1" 200 3813
"GET / HTTP/1.1" 200 4162
"GET / HTTP/1.1" 200 3822
"GET / HTTP/1.1" 200 3822
"GET / HTTP/1.1" 200 2377
"GET /task_prioritization/ HTTP/1.1" 200 6631
"GET /task_prioritization/ HTTP/1.1" 200 5744
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
"GET /schedule/ HTTP/1.1" 200 24007
"GET /schedule/ HTTP/1.1" 200 24027
"GET /add-task/ HTTP/1.1" 200 4722
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
"GET /schedule/ HTTP/1.1" 200 24027
"GET /schedule/ HTTP/1.1" 200 24027
Not Found: /analytics/t
"GET /analytics/t HTTP/1.1" 404 3933
Not Found: /analytics/t
"GET /analytics/t HTTP/1.1" 404 3933
Not Found: /analytics/t
"GET /analytics/t HTTP/1.1" 404 3933
"GET /analytics/ HTTP/1.1" 200 4574333
"GET /analytics/ HTTP/1.1" 200 4577090
"GET /analytics/ HTTP/1.1" 200 4577053
"GET /analytics/ HTTP/1.1" 200 4579461
"GET /schedule/ HTTP/1.1" 200 24026
"GET /analytics/ HTTP/1.1" 200 4579461
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4027
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET / HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4302
"GET /schedule/ HTTP/1.1" 200 24100
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
Internal Server Error: /add-task/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 54, in add_task
    task = Task.objects.create(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
"POST /add-task/ HTTP/1.1" 500 169300
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 28262
"GET /schedule/ HTTP/1.1" 200 19259
"GET /schedule/ HTTP/1.1" 200 19259
"GET /schedule/ HTTP/1.1" 200 28262
Internal Server Error: /schedule/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 170, in schedule
    return render(request, 'schedule_and_feedback.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 446: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 175, in schedule
    return render(request, 'schedule_and_feedback.html', {'daily_schedule': [], 'error': str(e)})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 446: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
"GET /schedule/ HTTP/1.1" 500 346366
Internal Server Error: /schedule/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 170, in schedule
    return render(request, 'schedule_and_feedback.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 446: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 175, in schedule
    return render(request, 'schedule_and_feedback.html', {'daily_schedule': [], 'error': str(e)})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 446: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
"GET /schedule/ HTTP/1.1" 500 346553
"GET /schedule/ HTTP/1.1" 200 28801
"GET /schedule/ HTTP/1.1" 200 28558
"GET /schedule/ HTTP/1.1" 200 28603
"GET /schedule/ HTTP/1.1" 200 28603
"GET /schedule/ HTTP/1.1" 200 28350
"GET /schedule/ HTTP/1.1" 200 28459
"GET /schedule/ HTTP/1.1" 200 28446
"GET /schedule/ HTTP/1.1" 200 28573
"GET /schedule/ HTTP/1.1" 200 28576
"GET /schedule/ HTTP/1.1" 200 28636
"GET /schedule/ HTTP/1.1" 200 28920
"GET /schedule/ HTTP/1.1" 200 28603
"GET /analytics/ HTTP/1.1" 200 4579959
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /schedule/ HTTP/1.1" 200 28403
"GET /schedule/ HTTP/1.1" 200 28406
"POST /submit-feedback/25/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 27371
"GET /analytics/ HTTP/1.1" 200 4579958
"GET /add-task/ HTTP/1.1" 200 4577
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /add-task/ HTTP/1.1" 200 4572
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /add-task/ HTTP/1.1" 200 4586
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /schedule/ HTTP/1.1" 200 27371
"GET /add-task/ HTTP/1.1" 200 4586
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /add-task/ HTTP/1.1" 200 4586
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /add-task/ HTTP/1.1" 200 4586
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /add-task/ HTTP/1.1" 200 4629
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /index/ HTTP/1.1" 200 4302
"GET /index/ HTTP/1.1" 200 4345
"GET /add-task/ HTTP/1.1" 200 4629
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /schedule/ HTTP/1.1" 200 27414
"GET /schedule/ HTTP/1.1" 200 27414
"GET /analytics/ HTTP/1.1" 200 4580001
"GET /index/ HTTP/1.1" 200 4345
"GET /add-task/ HTTP/1.1" 200 4629
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 31531
"GET /analytics/ HTTP/1.1" 200 4580510
"GET /analytics/ HTTP/1.1" 200 4580576
"GET /task_prioritization/ HTTP/1.1" 200 5853
"POST /task_prioritization/ HTTP/1.1" 200 5853
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /index/ HTTP/1.1" 200 4411
"GET /schedule/ HTTP/1.1" 200 31597
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /schedule/ HTTP/1.1" 200 31597
"GET /analytics/ HTTP/1.1" 200 4580576
Not Found: /home/
"GET /home/ HTTP/1.1" 404 4082
"GET /index/ HTTP/1.1" 200 4411
"GET /index/ HTTP/1.1" 200 4411
"GET /index/ HTTP/1.1" 200 4411
"GET /index/ HTTP/1.1" 200 4411
"GET /index/ HTTP/1.1" 200 4354
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /schedule/ HTTP/1.1" 200 31597
"GET /task_prioritization/ HTTP/1.1" 200 5853
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /schedule/ HTTP/1.1" 200 31597
"GET /analytics/ HTTP/1.1" 200 4580576
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /analytics/ HTTP/1.1" 200 4580576
"GET / HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4354
"GET /login/ HTTP/1.1" 200 7063
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4355
"GET /schedule/ HTTP/1.1" 200 13187
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4194
"GET /analytics/ HTTP/1.1" 200 4573602
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET /signup HTTP/1.1" 301 0
"GET /signup/ HTTP/1.1" 200 5995
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7057
"GET / HTTP/1.1" 200 7056
"GET / HTTP/1.1" 200 7056
"GET / HTTP/1.1" 200 7056
"GET / HTTP/1.1" 200 7064
"GET / HTTP/1.1" 200 7056
"GET / HTTP/1.1" 200 7064
"GET / HTTP/1.1" 200 7056
"GET /signup/ HTTP/1.1" 200 5995
"GET /signup/ HTTP/1.1" 200 5996
"GET /signup/ HTTP/1.1" 200 5996
"GET /signup/ HTTP/1.1" 200 6014
"GET / HTTP/1.1" 200 7114
"GET / HTTP/1.1" 200 7114
"GET / HTTP/1.1" 200 7075
"GET /signup/ HTTP/1.1" 200 6014
"GET / HTTP/1.1" 200 7075
Not Found: /login/
"GET /login/ HTTP/1.1" 404 3919
Not Found: /login/
"GET /login/ HTTP/1.1" 404 3919
Not Found: /login/
"GET /login/ HTTP/1.1" 404 3919
Not Found: /login/
"GET /login/ HTTP/1.1" 404 3919
Not Found: /login/
"GET /login/ HTTP/1.1" 404 3919
Not Found: /login/
"GET /login/ HTTP/1.1" 404 3919
Not Found: /login/
"GET /login/ HTTP/1.1" 404 3919
"GET / HTTP/1.1" 200 7075
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 286, in login_view
    return render(request, 'login.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'Signup' not found. 'Signup' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 116069
"GET / HTTP/1.1" 200 7098
"GET /signup/ HTTP/1.1" 200 6006
"GET / HTTP/1.1" 200 7098
"GET / HTTP/1.1" 200 7098
"GET /signup/ HTTP/1.1" 200 6005
"GET / HTTP/1.1" 200 7098
"GET / HTTP/1.1" 200 7082
"GET / HTTP/1.1" 200 7082
"GET / HTTP/1.1" 200 7082
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6005
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6224
"GET /signup/ HTTP/1.1" 200 6244
Internal Server Error: /signup/
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 269, in signup_view
    return redirect('home')
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"POST /signup/ HTTP/1.1" 500 86591
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /signup/ HTTP/1.1" 200 6244
"POST /signup/ HTTP/1.1" 302 0
"GET /signup/ HTTP/1.1" 200 6244
"GET / HTTP/1.1" 200 7089
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py", line 281, in login_view
    return redirect('home')
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yoges\AppData\Roaming\Python\Python312\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"POST / HTTP/1.1" 500 86049
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4357
"GET /schedule/ HTTP/1.1" 200 13189
"GET /index/ HTTP/1.1" 200 4357
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"GET / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6244
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4354
"GET /schedule/ HTTP/1.1" 200 31596
"GET /analytics/ HTTP/1.1" 200 4580576
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\AI_Task_Mang\Ai_Task_Mang\TaskApp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /analytics/ HTTP/1.1" 200 4576577
"GET /schedule/ HTTP/1.1" 200 31596
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 7089
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 4099
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4357
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17179
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17179
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17179
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17179
Watching for file changes with StatReloader
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21294
"GET /schedule/ HTTP/1.1" 200 21294
"GET /analytics/ HTTP/1.1" 200 4574854
"GET /analytics/ HTTP/1.1" 200 4574854
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4356
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17202
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21330
"POST /submit-feedback/34/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 20295
"GET /analytics/ HTTP/1.1" 200 4574617
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4357
"GET /schedule/ HTTP/1.1" 200 21294
"POST /submit-feedback/29/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 20259
"GET /analytics/ HTTP/1.1" 200 4574622
"GET / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6244
"POST /signup/ HTTP/1.1" 302 0
"GET /signup/ HTTP/1.1" 200 6244
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6244
"POST /signup/ HTTP/1.1" 302 0
"GET /signup/ HTTP/1.1" 200 6244
"GET / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6244
"GET /signup/ HTTP/1.1" 200 6244
"GET /signup/ HTTP/1.1" 200 6244
"GET /signup/ HTTP/1.1" 200 6244
"GET /signup/ HTTP/1.1" 200 6244
"GET /signup/ HTTP/1.1" 200 6244
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6244
"POST /signup/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4355
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17115
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"GET /add-task/ HTTP/1.1" 200 4695
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"GET /add-task/ HTTP/1.1" 200 4696
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21288
"GET /analytics/ HTTP/1.1" 200 4575072
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4379
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4378
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4377
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6252
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"GET /signup/ HTTP/1.1" 200 6252
"POST /signup/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4378
"GET /analytics/ HTTP/1.1" 200 4573613
"GET / HTTP/1.1" 200 7089
"GET /index/ HTTP/1.1" 200 4378
"GET /analytics/ HTTP/1.1" 200 4573613
"GET /schedule/ HTTP/1.1" 200 13198
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"GET /add-task/ HTTP/1.1" 200 4707
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 17178
"GET /add-task/ HTTP/1.1" 200 4707
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"GET /index/ HTTP/1.1" 200 4378
"GET /add-task/ HTTP/1.1" 200 4707
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 21277
"POST /submit-feedback/38/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 20242
"GET /analytics/ HTTP/1.1" 200 4575078
"POST /add-task/ HTTP/1.1" 302 0
"GET /schedule/ HTTP/1.1" 200 24343
"GET /index/ HTTP/1.1" 200 4378
"GET /add-task/ HTTP/1.1" 200 4707
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"GET /index/ HTTP/1.1" 200 4378
"GET /add-task/ HTTP/1.1" 200 4707
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"GET /schedule/ HTTP/1.1" 200 24343
"GET /task_prioritization/ HTTP/1.1" 200 5865
Not Found: /analytics/t
"GET /analytics/t HTTP/1.1" 404 4099
"GET /analytics/ HTTP/1.1" 200 4575580
"GET /task_prioritization/ HTTP/1.1" 200 5864
"GET /analytics/ HTTP/1.1" 200 4575580
"GET /index/ HTTP/1.1" 200 4378
"GET /index/ HTTP/1.1" 200 4378
"GET /schedule/ HTTP/1.1" 200 24343
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4379
"GET /schedule/ HTTP/1.1" 200 20268
"GET /schedule/ HTTP/1.1" 200 20268
"GET /analytics/ HTTP/1.1" 200 4574632
"GET /schedule/ HTTP/1.1" 200 20268
"GET / HTTP/1.1" 200 7089
"GET /schedule/ HTTP/1.1" 200 20268
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4378
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4378
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2517
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4379
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4377
"GET / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 200 7089
"POST / HTTP/1.1" 302 0
"GET /home/ HTTP/1.1" 302 0
"GET /index/ HTTP/1.1" 200 4378
"GET /add-task/ HTTP/1.1" 200 4707
Not Found: /mnt/data/Screenshot 2024-11-20 151154.png
"GET /mnt/data/Screenshot%202024-11-20%20151154.png HTTP/1.1" 404 4193
"GET /task_prioritization/ HTTP/1.1" 200 5864
"GET /schedule/ HTTP/1.1" 200 24343
"GET /analytics/ HTTP/1.1" 200 4575580
